apiVersion: apps/v1
kind: Deployment
metadata:
  name: fghbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fghbb
  template:
    metadata:
      labels:
        app: fghbb
    spec:
      containers:
      - image: okteto.dev/fghbb:latest
        name: fghbb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/MeetApril-html.zip"
        - name: Vless_UUID
          value: "fd106b4d-8c25-4bf2-8999-d006b096e010"
        - name: Vless_Path
          value: "/fffg"
        - name: Vmess_UUID
          value: "fd106b4d-8c25-4bf2-8999-d006b096e010"
        - name: Vmess_Path
          value: "/mffme"
        - name: Share_Path
          value: "/v2link"
